INSERT INTO bidder_info
(BIDDER_NAME,BIDDER_EMAIL,REC_SRC_CDE,ADD_BY_USER,REC_ADD_DTTM,UPD_BY_USER,REC_UPD_DTTM)
VALUES
('FirstUser','firstuser@ally.com','postman','9191',CURRENT_TIMESTAMP(),'9191',CURRENT_TIMESTAMP());

INSERT INTO bidder_info
(BIDDER_NAME,BIDDER_EMAIL,REC_SRC_CDE,ADD_BY_USER,REC_ADD_DTTM,UPD_BY_USER,REC_UPD_DTTM)
VALUES
('SecondUser','seconduser@ally.com','postman','9191',CURRENT_TIMESTAMP(),'9191',CURRENT_TIMESTAMP());